### ISSUE TITLE
User Story: As a BlueConnect user I want to be able to connect to a device while other devices are already connected. This is done when a connection can be established without interrupting connectivity or functionality of other devices.

### ISSUE THREAD

**Issue by BipbopBohnfon** [ChicoState/BlueConnect#7]

**Comment by acderosas** [comment]
Example: As a person living in a dorm, I want to be able to connect more devices to an already established audio setup (E.g., Dorm mates have speakers, a computer, and a TV, etc.) without having an awkward connection (Stuttering, etc.).

**Comment by acderosas** [comment]
Second Sprint Priority
